any_skills = {
    'animal training': ['demigryph', 'dog', 'horse', 'pegasus', 'pigeon'],
    'art': ['cartography', 'engraving', 'mosaics', 'painting', 'sculpture', 'tattoo', 'weaving'],
    'channeling': ['beasts','death','fire','heavens','life','light','metal','shadow'],
    'entertain': ['acting', 'comedy', 'singing', 'storytelling'],
    'language': ['albion', 'battle tongue', 'bretonnian', 'classical', 'eltharin', 'estalian', 'gospodarinyi', 'grumbarth', 'guilder', 'khazalid', 'magick', 'mootish', 'norse', 'queekish', 'reikspiel', 'thieves tongue', 'tilean', 'wastelands'],
    'lore': ['engineering','geology','heraldry','history','law','magick','metallurgy','politics','science','theology','undead'],
    'melee': ['basic', 'brawling', 'cavalry', 'fencing', 'flail', 'parry', 'pole-arm', 'two-handed'],
    'perform': ['acrobatics', 'clowning', 'dancing', 'firebreathing', 'juggling', 'miming', 'rope walking'],
    'play': ['bagpipe', 'lute', 'harpsichord', 'horn', 'violin'],
    'ranged': ['blackpowder', 'bow', 'crossbow', 'engineering', 'entangling', 'explosives', 'sling', 'throwing'],
    'ride': ['demigryph', 'great wolf', 'griffon', 'horse', 'pegasus'],
    'sail': ['barge', 'caravel', 'cog', 'frigate', 'wolfship'],
    'secret signs': ['grey order', 'guilder', 'ranger', 'scout', 'thief', 'vagabond'],
    'stealth': ['rural', 'underground', 'urban'],
    'trade': ['alchemist','apothecary','calligrapher', 'chandler', 'carpenter', 'cook', 'embalmer', 'smith', 'tanner', 'poisoner']}


skill_chars = {
    'animal care': 'Int',
    'animal training': 'Int',
    'art': 'Dex',
    'athletics': 'Ag',
    'augury': 'Int',
    'bribery': 'Fel',
    'channeling': 'WP',
    'charm': 'Fel',
    'charm animal': 'WP',
    'climb': 'S',
    'consume alcohol': 'T',
    'cool': 'WP',
    'dodge': 'Ag',
    'drive': 'Ag',
    'endurance': 'T',
    'entertain': 'Fel',
    'evaluate': 'Int',
    'gamble': 'Int',
    'gossip': 'Fel',
    'haggle': 'Fel',
    'heal': 'Int',
    'intimidate': 'S',
    'intuition': 'I',
    'language': 'Int',
    'leadership': 'Fel',
    'lore': 'Int',
    'melee': 'WS',
    'navigation': 'I',
    'outdoor survival': 'Int',
    'perception': 'I',
    'perform': 'Ag',
    'pick lock': 'Dex',
    'play': 'Dex',
    'pray': 'Fel',
    'psychometry': 'Int',
    'ranged': 'BS',
    'research': 'Int',
    'ride': 'Ag',
    'row': 'S',
    'sail': 'Ag',
    'secret signs': 'Int',
    'set trap': 'Dex',
    'sleight of hand': 'Dex',
    'stealth': 'Ag',
    'swim': 'S',
    'track': 'I',
    'trade': 'Dex'
}
