
#this is a character created but that hasn't been advanced yet
mock_slayer = {
    'level': 2,
    'gender': 'male',
    'species': 'dwarf',
    'career': 'slayer',
    'name': 'Krastert Steeledge of clan Firehelm',
    'age': 52,
    'eyeColour': 'Copper',
    'hairColour': 'Copper',
    'height': '4\'11"',
    'attributes': [45, 23, 30, 40, 30, 19, 37, 30, 55, 17, 0, 2, 2, 3],
    'movement': 3,
    'fate': [1, 3],
    'skills': [{'language (khazalid)': 0, 'lore (dwarfs)': 0, 'lore (geology)': 0,
                'lore (metallurgy)': 0, 'trade (chandler)': 0, 'intimidate': 5, 'evaluate': 5,
                'entertain (storytelling)': 3},
               {'consume alcohol': 3, 'cool': 9, 'dodge': 9, 'endurance': 9, 'gamble': 6,
                'heal': 2, 'lore (trolls)': 5, 'melee (basic)': 8}],
    'speciesTalents': ['magic resistance', 'night vision', 'read/write', 'resolute',
                       'sturdy'], 
    'careerTalents': ['magic resistance', 'night vision', 'read/write',
                                                    'resolute', 'sturdy', 'frenzy'],
    'wealth': ['4 pennies'],
    'classTrappings': ['clothing', 'hand weapon', 'dagger', 'pouch'],
    'careerTrappings': ['axe', 'flask of spirits', 'shame', 'tattoos', 'great axe',
                        'jewellery', "troll's head"]}

mock_slayer2 = {
    'level': 3,
    'gender': 'male',
    'species': 'dwarf',
    'career': 'slayer',
    'name': 'Krastert Steeledge of clan Firehelm',
    'age': 52,
    'eyeColour': 'Copper',
    'hairColour': 'Copper',
    'height': '4\'11"',
    'attributes': [45, 23, 30, 40, 30, 19, 37, 30, 55, 17, 0, 2, 2, 3],
    'movement': 3,
    'fate': [1, 3],
    'skills': [{'language (khazalid)': 0, 'lore (dwarfs)': 0, 'lore (geology)': 0,
                'lore (metallurgy)': 0, 'trade (chandler)': 0, 'intimidate': 5, 'evaluate': 5,
                'entertain (storytelling)': 3},
               {'consume alcohol': 3, 'cool': 9, 'dodge': 9, 'endurance': 9, 'gamble': 6,
                'heal': 2, 'lore (trolls)': 5, 'melee (basic)': 8}],
    'speciesTalents': ['magic resistance', 'night vision', 'read/write', 'resolute',
                       'sturdy'], 
    'careerTalents': ['magic resistance', 'night vision', 'read/write',
                                                    'resolute', 'sturdy', 'frenzy'],
    'wealth': ['4 pennies'],
    'classTrappings': ['clothing', 'hand weapon', 'dagger', 'pouch'],
    'careerTrappings': ['axe', 'flask of spirits', 'shame', 'tattoos', 'great axe',
                        'jewellery', "troll's head","giant's head",'throwing axes']}

mock_slayer3 = {
    'level': 4,
    'gender': 'male',
    'species': 'dwarf',
    'career': 'slayer',
    'name': 'Krastert Steeledge of clan Firehelm',
    'age': 52,
    'eyeColour': 'Copper',
    'hairColour': 'Copper',
    'height': '4\'11"',
    'attributes': [45, 23, 30, 40, 30, 19, 37, 30, 55, 17, 0, 2, 2, 3],
    'movement': 3,
    'fate': [1, 3],
    'skills': [{'language (khazalid)': 0, 'lore (dwarfs)': 0, 'lore (geology)': 0,
                'lore (metallurgy)': 0, 'trade (chandler)': 0, 'intimidate': 5, 'evaluate': 5,
                'entertain (storytelling)': 3},
               {'consume alcohol': 3, 'cool': 9, 'dodge': 9, 'endurance': 9, 'gamble': 6,
                'heal': 2, 'lore (trolls)': 5, 'melee (basic)': 8}],
    'speciesTalents': ['magic resistance', 'night vision', 'read/write', 'resolute',
                       'sturdy'], 
    'careerTalents': ['magic resistance', 'night vision', 'read/write',
                                                    'resolute', 'sturdy', 'frenzy'],
    'wealth': ['4 pennies'],
    'classTrappings': ['clothing', 'hand weapon', 'dagger', 'pouch'],
    'careerTrappings': ['axe', 'flask of spirits', 'shame', 'tattoos', 'great axe',
                        'jewellery', "troll's head","giant's head",'throwing axes']}
