
repurchasable_talents = [
    'accurate shot',
    'acute sense',
    'aethyric attunement',
    'alley cat',
    'ambidextrous',
    'animal affinity',
    'argumentative',
    'artistic',
    'attractive',
    'battle rage',
    'beat blade',
    'beneath notice',
    'berserker charge',
    'blather',
    'bookish',
    'break and enter',
    'briber',
    'cardsharp',
    'careful strike',
    'carouser',
    'catfall',
    'cat-tongued',
    'combat aware',
    'combat master',
    'combat reflexes',
    'commanding presence',
    'concoct',
    'contortionist',
    'crack the whip',
    'craftsman',
    'dealmaker',
    'detect artefact',
    'diceman',
    'dirty fighting',
    'disarm',
    'distract',
    'drilled',
    'dual wielder',
    'embezzle',
    'enclosed fighter',
    'etiquette',
    'fast hands',
    'fast shot',
    'fearless',
    'feint',
    'field dressing',
    'fisherman',
    'flagellant',
    'flee!',
    'frightening',
    'furious assault',
    'gregarious',
    'gunner',
    'hardy',
    'hatred',
    'holy hatred',
    'holy visions',
    "hunter's eye",
    'impassioned zeal',
    'implacable',
    'in-fighter',
    'inspiring',
    'instinctive diction',
    'iron jaw',
    'iron will',
    'linguistics',
    'lip reading',
    'luck',
    'magical sense',
    'master of disguise',
    'master orator',
    'master tradesman',
    'menacing',
    'mimic',
    'night vision',
    'nose for trouble',
    'numismatics',
    'old salt',
    'orientation',
    'panhandle',
    'perfect pitch',
    'pharmacist',
    'pilot',
    'public speaker',
    'pure soul',
    'rapid reload',
    'reaction strike',
    'relentless',
    'resistance',
    'resolute',
    'reversal',
    'riposte',
    'river guide',
    'robust',
    'roughrider',
    'rover',
    'savant',
    'scale sheer surface',
    'schemer',
    'sea legs',
    'seasoned traveller',
    'second sight',
    'secret identity',
    'shadow',
    'shieldsnab',
    'sixth sense',
    'sniper',
    'speedreader',
    'sprinter',
    'step aside',
    'stone soup',
    'stout-hearted',
    'strider',
    'strike mighty blow',
    'strike to injure',
    'strike to stun',
    'strong back',
    'strong legs',
    'strong-minded',
    'strong swimmer',
    'sturdy',
    'super numerate',
    'supportive',
    'sure shot',
    'surgery',
    'tenacious',
    'tinker',
    'tower of memories',
    'trapper',
    'trick riding',
    'tunnel rat',
    'unshakable',
    'war leader',
    'waterman',
    'well-prepared',
    'witch!']


detailed_talents = {'arcane magic': ['beasts', 'death', 'fire','heavens','metal','shadow','light','life'],
                    'acute sense': [ 'sight', 'hearing', 'taste', 'smell', 'touch'],
                    
                    'bless': ['manann','morr','myrmidia','ranald','rhya','shallya','sigmar','sigmar','sigmar','taal','ulric','verena'], 
                    'craftsman': [ 'alchemist','apothecary', 'calligrapher', 'chandler',
                     'carpenter', 'cook', 'embalmer', 'smith', 'tanner'],
                    'etiquette':[ 'criminals', 'cultists', 'guilders', 'nobles',
                     'scholars', 'servants', 'soldiers'],
                    'fearless': [ 'beastmen', 'greenskins', 'outlaws', 'vampires',
                     'watchmen', 'witches'],
                    'hatred': [ 'beastmen', 'greenskins', 'monsters', 'outlaws',
                     'sigmarites', 'undead', 'witches'],
                    'invoke': ['manann','morr','myrmidia','ranald','rhya','shallya','sigmar','sigmar','sigmar','taal','ulric','verena'], 
                    'master tradesman': [ 'alchemist','apothecary', 'calligrapher', 'chandler',
                     'carpenter', 'cook', 'embalmer', 'smith', 'tanner'],
                    'resistance': [ 'magic', 'poison', 'disease', 'mutation'],
                    'savant': [ 'alchemy','engineering', 'geology', 'heraldry', 'history', 'law',
                     'magick', 'metallurgy', 'science', 'theology'],
                    'strider':[ 'coastal', 'deserts', 'marshes',
                        'rocky', 'tundra', 'woodlands'],
                    'suffuse with': ['beasts', 'death', 'fire','heavens','metal','shadow','light','life'],

                    }


random_species_talents = ['acute sense (any)', 'ambidextrous', 'animal affinity', 'artistic', 'attractive', 'coolheaded', 'craftsman (any)', 'flee!', 'hardy', 'lightning reflexes', 'linguistics', 'luck', 'marksman', 'mimic', 'night vision',
                          'nimble fingered', 'noble blood', 'orientation', 'perfect pitch', 'pure soul', 'read/write', 'resistance (any)', 'savvy', 'sharp', 'sixth sense', 'strong legs', 'sturdy', 'suave', 'super numerate', 'very resilient', 'very strong', 'warrior born']


 
talent_list =  [ ['accurate shot','bs'], ['acute sense','i'], ['aethyric attunement','i'],
 ['alley cat','i'], ['ambidextrous','2'], ['animal affinity','wp'], ['argumentative','fel'],
 ['artistic','dex'], ['attractive','fel'], ['battle rage','wp'], ['beat blade','ws'],
 ['beneath notice','fel'], ['berserker charge','s'], ['blather','fel'], ['bookish','int'],
 ['break and enter','s'], ['briber','fel'], ['cardsharp','int'], ['careful strike','i'],
 ['carouser','t'], ['catfall','agi'], ['cat-tongued','fel'], ['combat aware','i'],
 ['combat master','agi'], ['combat reflexes','i'], ['commanding presence','fel'], ['concoct','int'],
 ['contortionist','agi'], ['crack the whip','dex'], ['craftsman','dex'],['crew commander','i'], ['dealmaker','fel'],
 ['detect artefact','i'], ['diceman','int'], ['dirty fighting','ws'], ['disarm','i'],
 ['distract','agi'], ['drilled','ws'], ['dual wielder','agi'], ['embezzle','int'],
 ['enclosed fighter','agi'], ['etiquette','fel'], ['fast hands','dex'], ['fast shot','agi'],
 ['fearless','wp'], ['feint','ws'], ['field dressing','int'], ['fisherman','i'],
 ['flagellant','t'], ['flee!','agi'], ['frightening','s'], ['furious assault','agi'],
 ['gregarious','fel'], ['gunner','dex'], ['hardy','t'], ['hatred','wp'],
 ['holy hatred','fel'], ['holy visions','i'], ["hunter's eye",'i'], ['impassioned zeal','fel'],
 ['implacable','t'], ['in-fighter','dex'], ['inspiring','fel'], ['instinctive diction','i'],
 ['iron jaw','t'], ['iron will','wp'], ['linguistics','int'], ['lip reading','i'],
 ['luck','fel'], ['magical sense','i'], ['master of disguise','fel'], ['master orator','fel'],
 ['master tradesman','dex'], ['menacing','s'], ['mimic','i'], ['night vision','i'],
 ['nose for trouble','i'], ['numismatics','i'], ['old salt','agi'], ['orientation','i'],
 ['panhandle','fel'], ['perfect pitch','i'], ['pharmacist','int'], ['pilot','i'],
 ['public speaker','fel'], ['pure soul','wp'], ['rapid reload','dex'], ['reaction strike','i'],
 ['relentless','agi'], ['resistance','t'], ['resolute','s'], ['reversal','ws'],
 ['riposte','agi'], ['river guide','i'], ['robust','t'], ['roughrider','agi'],
 ['rover','agi'], ['savant','int'], ['scale sheer surface','s'], ['schemer','int'],
 ['sea legs','t'], ['seasoned traveller','int'], ['second sight','i'], ['secret identity','int'],
 ['shadow','agi'], ['shieldsnab','s'], ['sixth sense','i'], ['sniper','4'], ['speedreader','int'],
 ['sprinter','s'], ['step aside','agi'], ['stone soup','t'], ['stout-hearted','wp'], ['strider','agi'],
 ['strike mighty blow','s'], ['strike to injure','i'], ['strike to stun','ws'], ['strong back','s'],
 ['strong legs','s'], ['strong-minded','wp'], ['strong swimmer','s'], ['sturdy','s'],
 ['super numerate','int'], ['supportive','fel'], ['sure shot','i'], ['surgery','int'],
 ['tenacious','t'], ['tinker','dex'], ['tower of memories','int'], ['trapper','i'],
 ['trick riding','agi'], ['tunnel rat','agi'], ['unshakeable','wp'], ['war leader','fel'],
 ['waterman','agi'], ['well-prepared','i'], ['witch!','wp']
 ]
